### ISSUE TITLE
[Issue] Missing hashes for *Strings.localized.min.js files for version 15.0.847.32

### ISSUE THREAD

**Issue by dstjean** [microsoft/CSS-Exchange#300]
The hashes for the files with pattern *Strings.localized.min.js in the 15.0.847.32 distribution are missing from the baseline

I found those files in the ISO of MS Exchange 2013 SP1 [mu_exchange_server_2013_with_sp1_x64_dvd_4059293.iso SHA-256 150A2FBA7B1D052C9A5D107A7A43FB98B1A007E662C1AE7C1A7B7F9D31C23E19]

[Hashes found on ISO.csv.txt](https://github.com/microsoft/CSS-Exchange/files/6124956/Hashes.found.on.ISO.csv.txt)

Very likely genuine but I'd like those hashes to come from Microsoft and be added to the baseline.

Thank you

**Comment by psykokwak4** [comment]
what's the script version? those localized.min.js files are in baseline:

9276F79DCE9AFC8DD7F9A3C904726BD06FFB5A4E88536ECE423D5D667CF916D5,15.0.847.32,\ClientAccess\owa\prem\version\ext\def\microsoft.exchange.clients.owa2.client.extensionstrings.localized.min.js

**Comment by dstjean** [comment]
This happened after running v21.03.11.1408.

**Comment by anshuldube** [comment]
Could you please retry with a latest release?

**Comment by anshuldube** [comment]
This should be fixed, please feel free to reopen if it persists.

**Comment by dstjean** [comment]
Still happening.

See results attached this is using v21.03.11.1736
[15.0.1497.2_result.csv.txt](https://github.com/microsoft/CSS-Exchange/files/6127217/15.0.1497.2_result.csv.txt)

**Comment by anshuldube** [comment]
investigating.

**Comment by psykokwak4** [comment]
also, RE on "Strings.localized.min.js" errors, we don't have them in baseline (not that we don't have those files)
closing this issue, and if baselines will be updated with *Strings.localized.min.js" hashes, this issue should be fixed
please check issue #313 for baseline release
and feel free to have this issue reopened
